/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Float, useGLTF } from '@react-three/drei'

const JavaScriptLogo = (props) => {
  const { nodes, materials } = useGLTF('models/javascript_logo.glb')
  return (
    <Float floatIntensity={0.5}>
      <group {...props} scale={3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve002.geometry}
          material={materials['Material.001']}
          position={[-0.038, -0.018, -0.035]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Curve004.geometry}
          material={materials['Material.001']}
          position={[0.056, 0.012, -0.032]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </Float>
  )
}

useGLTF.preload('models/javascript_logo.glb')

export default JavaScriptLogo
